### ISSUE TITLE
Create base `MatchBreakdown` view

### ISSUE THREAD

**Issue by ZachOrr** [the-blue-alliance/the-blue-alliance-react#11]
We should stop duplicating code, like `xImage` and `checkImage` methods by just creating a superclass

**Comment by dracco1993** [comment]
Oh yes, that would be nice to keep things DRY.

**Comment by Tavaru5** [comment]
Hey! For this, do we want to throw in the image functions like `upArrowImage` and `downArrowImage` from 2017? They're not reused anywhere currently, but they're set up similarly to xImage and checkImage and could potentially be reused in the future.
