### ISSUE TITLE
Add 2019 Scoring Location Breakdown to MatchBreakdown2019

### ISSUE THREAD

**Issue by ZachOrr** [the-blue-alliance/the-blue-alliance-react#12]
https://www.thebluealliance.com/match/2019week0_qm13

![image](https://user-images.githubusercontent.com/516458/52919371-dbdfb100-32cf-11e9-94ec-ff49ac57591e.png)

**Comment by dracco1993** [comment]
For reference, here is the corresponding code in the web app:
https://github.com/the-blue-alliance/the-blue-alliance/blob/master/templates_jinja2/match_partials/match_breakdown/match_breakdown_2019.html#L439

**Comment by dracco1993** [comment]
Added in #33  👍
