### ISSUE TITLE
Cargo added to hatch totals in matchbreakdown2019

### ISSUE THREAD

**Issue by cyocom** [the-blue-alliance/the-blue-alliance-react#15]
\# Cargo is always 0 in the match breakdowns, # Hatch Panels seems to have # Cargo added to it.

Example:
https://www.thebluealliance.com/match/2019week0_qm5
![img_1784](https://user-images.githubusercontent.com/19940/53042436-402b7d80-3454-11e9-95d2-17e541800ebe.PNG)

vs

<img width="580" alt="screen shot 2019-02-19 at 2 40 47 pm" src="https://user-images.githubusercontent.com/19940/53042483-605b3c80-3454-11e9-8bf6-41bc04b51943.png">

**Comment by dracco1993** [comment]
I'll look into it.
