### ISSUE TITLE
Update hatch panel and cargo rows to use icons

### ISSUE THREAD

**Issue by dracco1993** [the-blue-alliance/the-blue-alliance-react#20]
Icons from: https://material.io/tools/icons/?style=baseline

Null hatch panel: `trip_origin`/`#616161`
Hatch panel: `trip_origin`/`#ffeb3b`
Cargo: `lens`/`#ff6d00`

**Comment by dracco1993** [comment]
From Slack:
![image](https://user-images.githubusercontent.com/1204591/53304032-f4efe100-383e-11e9-8a3c-dc9d3cf995c8.png)

**Comment by ZachOrr** [comment]
Except lets get ours to align vertically haha
